### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by johanhugg** [cherfia/jotenberg#1]
Hi!

It would be awesome if this could be published to maven central so we don't have to fiddle with Github's horrible maven package hosting.

Thanks for the library, by the way!

**Comment by cherfia** [comment]
Hi @johanhugg, 
Thank you for your feedback and suggestion! I'm glad to hear that you find the library useful. 
The library is now available on Maven Central! 🚀 https://mvnrepository.com/artifact/dev.inaka/jotenberg

**Comment by valentinhttr** [comment]
Hello @cherfia 
I see that the versions are no longer published on Maven Central. Is there a reason for this?

**Comment by btocquec** [comment]
+1 ! It would be great and easier than github repo. Thanks for your work btw !
